[package]
name = "keyboard_to_twist"
version.workspace = true
edition.workspace = true

[dependencies]
ros2_utils.workspace = true
geometry_msgs.workspace = true
ros2-client.workspace = true
device_query.workspace = true
crossterm.workspace = true
libc = "0.2"
